### ISSUE TITLE
Container margin not set

### ISSUE THREAD

**Issue by CapsE** [buz-zard/tailwind-bootstrap-grid#17]
Hi, I just installed and included this library and I have an issue with the container class. "margin-left" and "margin-right" are not set and so my content sticks to the left of the screen.

I searched my code for other occurences of the container class but I have no definitions of it myself. In the webinspector I can see that the styles are not overriden but simply missing from the container class.

Do you have any idea what could cause this?

PS: I added my own definition of "container" and gave it the margin that way but this feels dirty...

**Comment by buz-zard** [comment]
Strange, the [demo setup](https://github.com/buz-zard/tailwind-bootstrap-grid/tree/master/demo) has the container class with margins  https://tailwind-bootstrap-grid.netlify.com/main.css

Are you using the https://tailwindcss.com/docs/container/ plugin also? I think it would overwrite the `.container` outputted by this plugin.

**Comment by CapsE** [comment]
Thank you for the quick response it helped alot. I added your plugin at the top of my config file completly overlooking I had a second plugin section at the bottom overriding the include. 

Definetly an error on my side but maybe you could update the readme to include a warning to replace the default tailwind plugin?

**Comment by buz-zard** [comment]
Good to know, will do.
